# Generated by Django 6.0.2 on 2026-02-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_basket_product_alter_basket_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together={('user', 'product')},
        ),
    ]
